INSERT INTO maestra_tipo_cambio (MONEDA_ORIGEN, MONEDA_DESTINO,TIPO_CAMBIO ,FECHA_CAMBIO) VALUES('USD', 'PER',4.08, NOW());
INSERT INTO maestra_tipo_cambio (MONEDA_ORIGEN, MONEDA_DESTINO,TIPO_CAMBIO ,FECHA_CAMBIO) VALUES('PER', 'USD',0.25, NOW());
INSERT INTO maestra_tipo_cambio (MONEDA_ORIGEN, MONEDA_DESTINO,TIPO_CAMBIO ,FECHA_CAMBIO) VALUES('EUR', 'PER',4.82, NOW());
INSERT INTO maestra_tipo_cambio (MONEDA_ORIGEN, MONEDA_DESTINO,TIPO_CAMBIO ,FECHA_CAMBIO) VALUES('PER', 'EUR',0.21, NOW());

